sonar.projectKey=kameshwaranvelu-ci-cd
sonar.organization=kameshwaranvelu

sonar.sources=.
sonar.exclusions=**/tests/**,**/test_*.py,**/venv/**
sonar.tests=.
sonar.test.inclusions=test_*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
