name: Infra (Terraform)

on:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/infra.yaml"
  pull_request:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/infra.yaml"

env:
  AWS_REGION: ap-south-1
  TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
  TF_VAR_app_repo_url: ${{ vars.APP_REPO_URL }}
  TF_VAR_app_repo_username: ${{ vars.APP_REPO_USERNAME }}
  TF_VAR_github_owner: ${{ vars.REPO_OWNER }}
  TF_VAR_repo_name: ${{ vars.REPO_NAME }}
  TF_VAR_gitops_pat: ${{ secrets.GITOPS_PAT }}

defaults:
  run:
    working-directory: infra

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.INFRA_CI_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - name: Run TFLint
        run: |
          tflint --init
          tflint
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
            additional_args: --config-file infra/.tfsec/config.yaml --minimum-severity HIGH
      - run: terraform plan -out=tfplan
      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tfplan

  apply:
    name: Terraform Apply
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.INFRA_CI_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - run: terraform init
      - run: terraform apply -auto-approve
